name: Publish onchain-issuer-demo
on:
  workflow_dispatch:

jobs:
  build_onchain_issuer_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout onchain-issuer-demo
        uses: actions/checkout@v3
        with:
          path: onchain-issuer-demo

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build file with supported networks
        run: |
          cd onchain-issuer-demo
          echo -e "polygon:mumbai:" > resolvers.settings.yaml
          echo -e "  contractState: ${{ vars.POLYGON_MUMBAI_CONTRACT_STATE_ADDRESS }}" >> resolvers.settings.yaml
          echo -e "  networkURL: ${{ secrets.POLYGON_MUMBAI_NODE_URL }}" >> resolvers.settings.yaml

      - name: Build file with supported onchain issuers.
        run: |
          cd onchain-issuer-demo
          echo -e "\"${{ vars.POLYGON_MUMBAI_ONCHAIN_ISSUER_CONTRACT }}\":" > onchain-issuer.settings.yaml
          echo -e "  networkURL: ${{ secrets.POLYGON_MUMBAI_NODE_URL }}" >> onchain-issuer.settings.yaml
          echo -e "  contractOwner: ${{ secrets.POLYGON_MUMBAI_ISSUER_OWNER }}" >> onchain-issuer.settings.yaml

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: build and deploy to GithubRegistry
        env:
          GITHUB_REF: ${{github.ref}}
        run: |
          ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
          echo GITHUB_REF - $ref
          cd onchain-issuer-demo && \
          docker buildx build --push \
           --platform linux/amd64 \
           -t ghcr.io/0xpolygonid/onchain-issuer-demo:${ref} \
           -t ghcr.io/0xpolygonid/onchain-issuer-demo:latest .
